# Page CMS config https://app.pagescms.org
media:
  input: content/images
  output: images
content:
  - name: posts
    label: Posts
    type: collection
    path: content/_posts
    view:
      fields: [title, draft, date_published, tags]
      primary: title
      sort: [date_published, desc]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug (URL), type: string }
      - { name: excerpt, label: Excerpt, type: text }
      - { name: feature_image, label: Feature Image, type: image }
      - { name: date_published, label: Date Published (ISO), type: date, options: { time: true } }
      - { name: date_updated, label: Date Updated (ISO), type: date, options: { time: true } }
      - { name: draft, label: Draft, type: boolean }
      - name: tags
        label: Tags
        type: string
        list: true
        description: 'Common tags: Nuôi dạy con, Nuôi con, Dạy con, Review, Chuyện chị em, Tự nhiên mà sống'
      - { name: body, label: Body, type: rich-text }

  - name: gioi-thieu
    label: 'Giới Thiệu'
    type: file
    path: content/gioi-thieu/index.md
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/page.njk }
      - { name: title, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: date_published, label: Date Published, type: date, options: { time: true } }
      - { name: date_updated, label: Date Updated, type: date, options: { time: true } }
      - { name: show_latest_posts, label: Show Latest Posts, type: boolean }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Display Name, type: string }
          - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }

  - name: nuoi-day-con
    label: 'Góc Nuôi Dạy Con'
    type: file
    path: content/nuoi-day-con/index.njk
    format: yaml-frontmatter
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/collection.njk }
      - { name: title, label: Title, type: string }
      - { name: collectionName, label: Collection Name (Tag), type: string }
      - { name: permalink, label: Permalink, type: string }
      - { name: description, label: Description, type: text }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Display Name, type: string }
          - { name: order, label: Order, type: number }

  - name: chuyen-chi-em
    label: 'Góc Chị Em'
    type: file
    path: content/chuyen-chi-em/index.njk
    format: yaml-frontmatter
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/collection.njk }
      - { name: title, label: Title, type: string }
      - { name: collectionName, label: Collection Name (Tag), type: string }
      - { name: permalink, label: Permalink, type: string }
      - { name: description, label: Description, type: text }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Display Name, type: string }
          - { name: order, label: Order, type: number }

  - name: review
    label: Góc Review
    type: file
    path: content/review/index.njk
    format: yaml-frontmatter
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/collection.njk }
      - { name: title, label: Title, type: string }
      - { name: collectionName, label: Collection Name (Tag), type: string }
      - { name: permalink, label: Permalink, type: string }
      - { name: description, label: Description, type: text }
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, label: Display Name, type: string }
          - { name: order, label: Order, type: number }

  - name: metadata
    label: Site Settings
    type: file
    path: _data/metadata.js
    format: code
    fields:
      - name: body
        label: Metadata Code
        type: code
        options:
          language: javascript
