module.exports = {
	title: 'Nuôi Dạy Con Blog',
	url: 'https://nuoidaycon.blog',
	language: 'vi',
	description: 'Blog nuôi dạy con - Chia sẻ kinh nghiệm chăm sóc và nuôi dạy con',
	logo: '/images/2020/06/ndc-logo.png',
	favicon: '/favicon.png',
	facebook: 'https://www.facebook.com/deconlontunhien',
	twitter: '',
	gtag: 'G-GSRQS8456P',
	author: {
		name: 'Thảo Nguyễn',
		email: '',
		url: 'https://nuoidaycon.blog',
		bio: 'Một bà mẹ 2 con chia sẻ về những điều căn bản, đơn giản và đem lại thanh thản trong việc chăm sóc, dạy dỗ con cái và cuộc sống thường ngày.',
		image: '/images/thao-avatar.png',
		website: '',
		facebook: 'deconlontunhien',
		twitter: '',
	},
}
